public/robots.txt
=> chore: 웹 크롤링 방지

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/pull_request_template.md
일단 잘 되는지 테스트용 && 기본적인 골격만 짜봤습니다
yml 잘 작성하시는 분 계시면 언제든지 수정 && 추가 환영합니다!
=> chore: :memo: PR && ISSUE 템플릿 추가

src/components/TempLayout/TempFooter.tsx, src/components/TempLayout/TempGNB.tsx, src/components/TempLayout/TempLayout.tsx
TempLayout 구현. 임시 GNB와 Footer로 구성
- 페이지 || 컴포넌트 변경 시 이미지 첨부 (기존과 다를 경우)
- `TempLayout.tsx` 컴포넌트 구현. 임시 GNB와 Footer로 구성되어 있습니다.
- `<TempLayout>` 태그로 작업하시는 페이지 감싸주시면 됩니다.
- 본문이 될 내용인 `children`은 `<main>` 태그로 감싸두었습니다. 참고 부탁드립니다.
=> feat: :sparkles: 임시 Layout 컴포넌트 구현

.eslintrc.json
- 줄바꿈 형식에 따른 오류를 표시하지 않게 하기 위해 `"auto"` 옵션 정의
=> Chore/eslint: 줄바꿈 형식에 따른 오류

Dockerfile
지난번 회의에서 yarn을 사용하기로 확정됨에 따라 빌드 오류를 해결하기 위해 yarn으로 Dockerfile에 명시 합니다.
Dockerfile에서 package-lock.json 삭제 후 yarn.lock을 복사 해 yarn을 통해 라이브러리 설치 및 배포하도록 수정합니다.
=> Chore/deploy-yarn: npm에서 yarn으로 변경됨에 따른 빌드 파일 수정

.github/workflows/deploy-staging-k8s.yaml
Dockerfile로 빌드 파이프라인이 변경됨에 따른 배포 스크립트 변경
GH Actions를 통한 배포 스크립트에 k8s yaml을 Node.js serve에서 nginx 기반 dockerfile로 수정합니다. (긴급)
=> :rocket: chore: 스테이징 환경에 Dockerfile 반영

src/components/Artist/ArtistMainScreenToggleButton.tsx
연관 이슈 없음
마크업 변경사항 없음
Component definition rule 부분은 수정하지 않음 (추후 논의 필요할 것으로 예상했음)
나머지 부분은 ESLint 에러 없음 확인
=> [FIX] 메인 페이지 Artist 섹션 ESLint 에 맞춰서 수정

src/components/News/NewsHeader.tsx, src/components/News/NewsHeaderButton.tsx, src/components/News/NewsThumnail.tsx, src/components/News/NewsThumnailList.tsx, src/components/News/NewsWeeklyEventBanner.tsx, src/components/News/color.ts
관련 이슈 없음
마크업 변경 없음
component definition rule 관련사항은 수정하지 않음 (lint: prefer-default-export)
앞선 PR과 동일하게 이 부분은 수정 방식 논의 필요하다고 느낌
나머지 ESLint 룰은 수정 완료
=> [FIX] 메인 페이지 News 섹션 ESLint fix

src/components/Movie/MovieSlider.tsx, src/components/Movie/svg/LeftArrow.tsx, src/components/Movie/svg/RightArrow.tsx, src/components/Movie/svg/index.ts
=> Fix/movie-eslint: lint 오류 해결

src/components/CommonLayout/Navbar.tsx, src/components/CommonLayout/Navbar/SubNav.tsx, src/components/layout.tsx
Layout, Navbar/SubNav쪽의 lint 문제를 해결합니다.
=> :rotating_light: fix: layout 측 lint 픽스

src/components/Chart/WeeklyAward.tsx
- `react-hooks/exhaustive-deps` 해결
=> Fix/chart-eslint: eslint warning 해결

src/styles/Global.tsx
- `<p>` tag margin 제거
- `<button>` margin, color, font reset, `cursor: pointer`
- `<a>` tag color inherit 추가
=> :lipstick: feat/global-css: reset css - p, button, a

src/components/CommonLayout/Navbar.tsx
SubNav를 활성화 하기 위한 클릭 이벤트가 일부 메뉴에 누락되어 작동하지 않는 문제를 수정합니다.
누락된 메뉴에 OnClick 이벤트를 추가합니다.
=> :bug: fix: 일부 메뉴에 누락된 subnav 활성 이벤트 추가

src/components/Artist/Artist.tsx, src/components/Artist/ArtistMainScreen.tsx, src/components/Artist/ArtistMainScreenToggleButton.tsx, src/components/Artist/ArtistMainScreenToggleButtonList.tsx, src/data/main-artist/artist-wallpaper.json, src/data/main-artist/button-icon.json
마크업 변경사항 없음
기존 JS 전역 오브젝트로 선언했던 데이터 json 파일로 이동
=> Refactor/main artist: ARTIST 섹션 데이터 JSON화

.github/workflows/deploy-k8s-frontend.yaml, .github/workflows/linting-frontend.yaml, next.config.js, package.json, src/data/subnav.json
- PR을 머지하기 전 및 개별 브랜치 별로 푸시 후에 lint를 자동으로 실행하도록 합니다.
- ![image](https://marshallku.com/wp-content/uploads/2022/05/Screen-Shot-2022-05-06-at-1.19.27-PM-1180x685.png)
- [Pull Request를 병합하기 전에 코드 검사하기 - marshallku.com](https://marshallku.com/dev/pull-request%eb%a5%bc-%eb%b3%91%ed%95%a9%ed%95%98%ea%b8%b0-%ec%a0%84%ec%97%90-%ec%bd%94%eb%93%9c-%ea%b2%80%ec%82%ac%ed%95%98%ea%b8%b0) 을 참고하여 lint를 GitHub Actions를 통해 실행되도록 하였습니다.
- 머지 후 아래와 같이 브랜치 룰에 CI 설정이 필요합니다. 
- ![image](https://marshallku.com/wp-content/uploads/2022/05/Screen-Shot-2022-05-06-at-12.04.18-PM-1180x1091.png) 
- Special Thanks to: @marshallku
=> :zap: Chore/lint-workflow: Pull Request를 병합하기 전/개별 브랜치 푸시 후에 코드 린트 검사

src/components/Movie/MovieSlider.tsx, src/components/Movie/style/Movie.Style.ts
- Fixes # (이슈 번호)
- 페이지 || 컴포넌트 변경 시 이미지 첨부 (기존과 다를 경우)
=> Refactor/main movie 추가사항 변경

src/components/MemberProfile/MemberProfile.css.ts, src/components/MemberProfile/MemberProfileCalendar.css.ts, src/components/MemberProfile/MemberProfileCalendar.tsx, src/components/MemberProfile/MemberProfileCalendarStreamList.css.ts, src/components/MemberProfile/MemberProfileTopBanner.tsx
- #62
https://github.com/ISEGYE-Universe/frontend/assets/65759076/6b5f4141-2764-497f-91f0-a3b2ab310de5
- 빌드 오류 해결
- 날짜 클릭 시 좌측 해당 일정 하이라이팅 로직 추가
- 디자인 컨펌나면 open 예정입니다.
- \>1920px 반응형 레이아웃 css 추가
=> Feat: chart-page: 차트 페이지 날짜 클릭 시 좌측 일정 하이라이팅 + 빌드 오류 해결

package.json, src/components/Chart/HistoryCarousel.tsx, src/components/Chart/Top100Chart.css.ts, src/components/Chart/Top100Chart.tsx, src/components/Chart/Top100Section.tsx, src/styles/Global.tsx, yarn.lock
- Closes #93 
- `querySelector`을 활용하여 좌표값 가져왔습니다.
- 개선하려 했으나 방법을 찾지 못함
- `HistoryCarousel`의 key가 겹치는 버그 해결
=> Feat/chart-page: 차트 영역 visx로 변경하여 구현, 가장 최근 데이터 말풍선 추가

src/components/Profile/ProfileIntroductionBox.tsx, src/data/profile.json, src/pages/profile/[memberName].tsx, src/pages/profile/gosegu.tsx, src/pages/profile/ine.tsx, src/pages/profile/jingburger.tsx, src/pages/profile/jururu.tsx, src/pages/profile/lilpa.tsx, src/pages/profile/viichan.tsx
- Closes #80 
- 다이나믹 라우팅 적용
- 원활한 적용을 위해 json 데이터 구조를 변경함
- minor css 수정
- font 두께 및 line-height 변경하였습니다.
=> Feat/profile-page: 프로필 페이지 다이나믹 라우팅 적용

.github/workflows/build-check.yaml
- PR 체크용 빌드 프로세스 추가
- PR 체크용 빌드 프로세스 추가
=> Chore/pr-check - PR 체크용 빌드 프로세스 추가
